language: bash
dist: xenial
services:
  - docker

env:
  global:
    - secure: KPplrms3QVtT8wyvXn4oGouxByxAHBNDS8jaG63QO9RxKJLsjudMIs+E2CNJwXQcfuXt4fnjsYI+zl+O+67DvoVgsIfLw0G2OgfMgtq7bUPPVRqrMcXabMNM4Owg7q4pym85LwZzEw3YQXzDZgXYsBW0CgFpEf65zHtR1kPVW+M=
    # If you want to see a list of installed packages in the doc-ci docker container, set to TRUE
    - LIST_PACKAGES=0

matrix:
  include:
    - name: "Validate Commit Message"
      language: python
      if: type = pull_request
      script:
      - pip install gitlint
      - wget https://raw.githubusercontent.com/SUSE-Cloud/automation/master/scripts/jenkins/gitlint.ini
      - gitlint --commits master..HEAD -C gitlint.ini
    - name: "Validate Documentation"
      before_install:
        - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST" >> env.list
        - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH" >> env.list
        - echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> env.list
        - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG" >> env.list
        - echo "LIST_PACKAGES=$LIST_PACKAGES" >> env.list
        - echo "PUBLISH_PRODUCTS=\"$PUBLISH_PRODUCTS\"" >> env.list
        - echo "ENCRYPTED_PRIVKEY_SECRET=$ENCRYPTED_PRIVKEY_SECRET" >> env.list
        - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT" >> env.list
        - wget https://raw.githubusercontent.com/openSUSE/doc-ci/feature/inc-docbook4travis/travis/travis.sh
        - ls
        - echo "Building docker image"
        - docker build -t sle-doc-image .
      script:
        - export DOCBOOK5_RNG_URI="file:///usr/share/xml/docbook/schema/rng/5.1/docbookxi.rnc"
        - docker run -e DOCBOOK5_RNG_URI --rm -it sle-doc-image /bin/bash -c '/bin/bash travis.sh'

notifications:
  email:
    on_success: change
    on_failure: always
